
from db_config import ENGINE_ADS_COURSEWORK_CHINA,ENGINE_ADS_COURSEWORK

ENGINE_ADS = ENGINE_ADS_COURSEWORK

MYSQL_USER = "root"
MYSQL_PASSWD = "lCU9eskWtqkz"
MYSQL_HOST_ENGLISH = "3.95.193.181"
MYSQL_PORT = 3306
# MYSQL_HOST_RUSSIAN = "35.173.190.93"
MYSQL_HOST_CHINA = 'rm-bp1f09qn5y3h3smvako.mysql.rds.aliyuncs.com'
MYSQL_PASSWD_CHINA = 'sv7tgB0mo2pzboRa'
MYSQL_USER_CHINA = "common"